---
- hosts: cpe
  gather_facts: false
  connection: local

  tasks:
   - name: show run 
     ios_command:
       commands:
         - show run   
     register: config

   - name: save output to ~/ansible_backups 
     copy: 
       content: "{{ config.stdout[0] }}"
       dest: "~/ansible_backups/show_run_{{ inventory_hostname }}.txt"
